### ISSUE TITLE
Confirm incompatibility with Chef 14

### ISSUE THREAD

**Issue by robbwagoner** [dragonsmith/timezone_lwrp#6]
Chef 14 was released today, 2014-04-03. `metadata.rb` claims this Cookbook is not compatible. Is that confirmed? or should a new release be made which removes the limitation? 

per the [RELEASE NOTES](https://github.com/chef/chef/blob/v14.0.190/RELEASE_NOTES.md#new-resources) there is not a native `timezone` resource in v14.

**Comment by dragonsmith** [comment]
@robbwagoner, hello! It is not confirmed, I was waiting for a release to test thoroughly. Will do that in the nearest days. Thanks for making an issue!

**Comment by dragonsmith** [comment]
Released v0.2.0. Closing.

Please open a new Issue, if you find any bugs.
